#!/bin/bash

set -ex

RAYLIB_CONFIG=`pkg-config --libs --cflags raylib`

if [ $# -lt 1 ]; then
    OUTPUT_DIR='-o bin/debug/inv'
    CC_FLAGS='-g -O0 -DDEBUG'
elif [ $1 = "debug" ]; then
    OUTPUT_DIR='-o bin/debug/inv'
    CC_FLAGS='-g -O0 -DDEBUG'
elif [ $1 = "release" ]; then
    OUTPUT_DIR='-o bin/release/inv'
    CC_FLAGS='-O3'
else
    echo "ERROR: Please enter 'debug', 'release', or neither."
    exit
fi

CC=clang
CSTD='-std=c99'

INCLUDE_DIR='-Isrc'

FILES='src/main.c'

$CC $CSTD $CC_FLAGS $OUTPUT_DIR $RAYLIB_CONFIG $INCLUDE_DIR $FILES
